### PR TITLE
add missing default translation strings

### PR DESCRIPTION
**Pull request by Morgy93**
Hello,

this adds some missing default translation strings:

- +32 000 000 000 [Reference](https://github.com/hyva-themes/magento2-hyva-checkout/blob/1.0.0-rc3/src/reactapp/src/components/shippingAddress/components/ShippingAddressForm.jsx#L155)
- Customer Information [Reference](https://github.com/hyva-themes/magento2-hyva-checkout/blob/1.0.0-rc3/src/reactapp/src/components/login/LoginMemorized.jsx#L15)
- Do you already have an account? [Reference](https://github.com/hyva-themes/magento2-hyva-checkout/blob/1.0.0-rc3/src/reactapp/src/components/login/components/LoginInfoBox.jsx#L44)
- Do you want to continue as guest user? [Reference](https://github.com/hyva-themes/magento2-hyva-checkout/blob/1.0.0-rc3/src/reactapp/src/components/login/components/LoginInfoBox.jsx#L22)
- john.doe@gmail.com [Reference](https://github.com/hyva-themes/magento2-hyva-checkout/blob/1.0.0-rc3/src/reactapp/src/components/login/components/LoginForm.jsx#L45)
- Loading... [Reference](https://github.com/hyva-themes/magento2-hyva-checkout/blob/1.0.0-rc3/src/reactapp/src/components/login/LoginMemorized.jsx#L15)
- Yes [Reference](https://github.com/hyva-themes/magento2-hyva-checkout/blob/1.0.0-rc3/src/reactapp/src/components/login/components/LoginInfoBox.jsx#L31)

### CODE REVIEW

**Comment by rajeev-k-tomy** [comment]
Looks good. But, it would be good if we update `src/i18n/en_US.csv` and `src/i18n/de_DE.csv` too with these string if they are not present.

**Comment by rajeev-k-tomy** [comment]
Also, target the PR to `1.0.0-rc` branch instead of `main` branch. Main branch is locked for the time being and all the updates must be now targetted to `1.0.0-rc` as you can see in other PRs.

**Comment by Morgy93** [comment]
> Looks good. But, it would be good if we update `src/i18n/en_US.csv` and `src/i18n/de_DE.csv` too with these strings if they are not present.

I did not know that the csv files are back again.

So we need to maintain translations at two different places now? Is this intended? Can you point me to any news for this?

**Comment by rajeev-k-tomy** [comment]
@Morgy93 `src/i18n` adds translations to Magento. It is the standard way a module introduces its own translation strings to the Magento application.

The initial approach was the JSON approach where the translations are used directly inside the react application. But the approach changed later and now, we are using Magento template translations. So basically, to add translations, we have two steps

1. Update `src/i18n/<localte>.csv` files.
2. Update the layout update xml file.

More details you can find in the doc: https://hyva-themes.github.io/magento2-hyva-checkout/i18n/

**Pull request closed without merging**
